### ISSUE TITLE
CME while saving chunks

### ISSUE THREAD

**Issue by maruohon** [alexbobp/BTFU#2]
I occasionally get CME errors while BTFU is trying to save the chunks on my server. I don't know if this is caused by some mod doing something in a thread, or does BTFU do the saving in a thread, or what...?

These errors seem to happen very randomly, sometimes they don't happen for several hours, and then suddenly several errors happen all at once, and sometimes just the one. This server was started on 2016-08-02 and as of now (2016-08-13)  there are 298 of these errors in the server log.

The server is on MC 1.10.2, currently running Forge 2049
Here is the latest error from this morning and the current mod list: https://gist.github.com/maruohon/f355b86caed1c110e3fe977928ae013c

**Comment by alexbobp** [comment]
BTFU totally does do the saving in a thread!  I hadn't realized that wasn't allowed and I was trying to minimize the performance impact.  Should I be doing the saving in the main thread then?

**Comment by maruohon** [comment]
Well I'm fairly certain doing it in the main thread is the only way it can be done without problems. Pretty much nothing in Minecraft can be safely threaded without much hackery, except for some of the rendering stuff.

I don't know if doing it in a thread would work "safely" for certain server setups (with simple mods/just a few mods)? So maybe using a thread could be a config option, which would be disabled by default.

The backup solution I use on my vanilla (and older modded servers) is just running save-off, save-all, do backup, save-on from a bash script run from a cron job. So I guess my preferred solution for BTFU backup routine would be about the same, maybe having the save-off/save-on and the save-all commands/steps as config options, since the saving normally happens every 45 seconds anyway, unless the admin has disabled it for the server, in which case doing the save-all before a backup would be required.

So personally I would like to be able to configure BTFU to follow the same procedure.

I would also like to have config options for the number of backups to keep, and the backup interval. What do you think about adding those? Because for the type of servers I run, doing backups every 5 minutes is just pointless, I would rather do it every 30 or 60 minutes. That way the older backups wouldn't get cycled out that quickly either.

**Comment by alexbobp** [comment]
The number of backups is already configurable.  As for the interval, the backup pruning follows a logarithmic pattern so raising the interval would have very little effect on the density of older backups.

I will just make it always save-all on the main thread.  If saving on a separate thread isn't always safe, then I don't want to do it.  I don't want a "performance vs correctness" option to tempt people into making the wrong choice.

**Comment by alexbobp** [comment]
Ok so I threw the code together to push these bits to the main thread, but it's late and I really need to go to sleep.  I'm not gonna be a jerk and ask you to do my testing for me when I haven't done any, but in case you really want the fix fast, I hosted it at https://capitalthree.pwnz.org/BTFU-1.9.4-1.6.jar for you to try at your own risk.  I'll find time soon to test it properly before I put it on curse and backport this change to 1.8 and 1.7.

**Comment by unascribed** [comment]
```
The backup solution I use on my vanilla (and older modded servers) is just running save-off, save-all, do backup, save-on from a bash script run from a cron job.
```
BTFU does precisely this, and then uses Unix tools to copy the world to another place. (Which is why it's awesome. :P)

Doing the saving from another thread is *mostly* safe, as it just submits work to a queue, which is then picked up by the main thread. **But**, this work queue is not thread safe. In rare cases, the main thread and the BTFU thread could clash and cause a CoModEx.

@alexbobp, if this is what caused all the errors at BTM, I will light you on fire.

**Comment by alexbobp** [comment]
okay, I finally understand what @unascribed said, I think.  my previous fix would "work" but is dumb.  I will do this better.

**Comment by alexbobp** [comment]
@maruohon ok I've confirmed, the workaround I used in that build I linked is the correct fix.  I'm uploading the same file to curse now.
